### PR TITLE
Closes #113: Added and adjusted Sensirion PCB

### LINKED ISSUE #67: Cable for Sensirion SFM3300-D

### LINKED ISSUE #113: Sensirion control PCB adjustments
Phoenix connector needs to move inboard to avoid issues with mounting to Sensirion sensor.
Needed for Issue #67 

### Current distance (center to center):
Phoenix pins to pogo pins = 9.705mm
Phoenix pins to board face = 6.721mm

### Constraints:
Distance pogo pins to front of sensirion cut out = 9.597mm - 0.862mm = 8.735mm [bumpouts on inside of Sensirion cutout]
Phoenix connector to control board PCB component = 1.938mm (max distance phoenix connector can move backwards, see image below)

#### Image of interference
image

#### Pogo pins to front wall (subtract 0.862mm for bump-out, center to edge)
image

#### Current space between pogo pins and phoenix connector pins (center to center)
image

#### Current phoenix pins to board (center to face):
image

#### Phoenix pins to Sensirion PCB component:
image

#### Second view:
image

#### Space between rear of (current) phoenix connector to control board PCB component:
image

### PR DESCRIPTION
**Pull request by hydronics2**
@Burhan-Q ... check this out..
- added sensirion connector PCB
- moved phoenix connector to be 8.4mm or 0.33" from pogo_pins

### CODE REVIEW

**Review by Burhan-Q — APPROVED** [review]
Looks good to me, approving pull request. @mechatroniks-git if you have a chance, please double check in case there's anything more you require

**Comment by Burhan-Q** [comment]
@capsulecorplab reviewed and approved. Wasn't sure if I should rebase or squash, so I'll leave that to you and maybe we can chat about this process when you have a chance.

**Comment by fpdotmonkey** [comment]
Got the PCB printed. Just waiting on a print of the clip so I can check the fit. I tried to print the header pins with this, but the broke off with the support material. image

**Comment by fpdotmonkey** [comment]
https://github.com/tetrabiodistributed/project-tetra/issues/67#issuecomment-669588910

**Review by fpdotmonkey — APPROVED** [review]
The board looks good.  There's some changes left to do on the clip, but I think it's safe to send out for like 10 of these boards.

**Pull request merged**
