### PR TITLE
Pi Updates

### LINKED ISSUE #129: Pi Hat design updates
- [ ] Hardware Port 1 for the Sensirion Sensor should correspond to software port 0
- [ ] The 50-pin connector to the Pi shouldn't allow for pins to be off by 1
- [x] The silkscreen for the buzzer should indicate which side is positive
- [x] There should be an interface for the software to hard reset the sensor

### PR DESCRIPTION
**Pull request by mechatroniks-git**

### CODE REVIEW

**Review by darraghbr — APPROVED** [review]
Looking much better, I appreciate the reworked file structure.

There are some files being removed as part of this commit, for example: 

'02_Development/FlowMeter/RPi Board/Sensor_manifold/v1/Manifold_v1.STEP'

Is this on purpose? Are these surplus to requirements and are they repeated elsewhere?

**Comment by hydronics2** [comment]
the V2 STEP file looks like it matches the current hole pattern on the PCB.. 
image
where as V1 is the old manifold/hole pattern
image

**Comment by mechatroniks-git** [comment]
@hydronics2 @darraghbr Yes, I removed the older manifold that won't work with the PCB. V2 has the correct hole placement.

**Comment by darraghbr** [comment]
@mechatroniks-git 

I can also see a number of V2 files that are being removed?

image

**Comment by mechatroniks-git** [comment]
@darraghbr The mechanical files should be back now

**Comment by darraghbr** [comment]
All looks good, ready for merge.

**Review by darraghbr — APPROVED** [review]

**Review by darraghbr — APPROVED** [review]

**Pull request merged**
